---

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  register: sriov_dkms_update_initramfs
  changed_when: sriov_dkms_update_initramfs.rc == 0
  when: ansible_os_family == 'Debian'
  notify: Reboot

- name: Reboot
  ansible.builtin.reboot:
  when: auto_reboot | default(true)
